# Metadados do Site
site_name: PI1 | Grupo 2
site_description: Documentação técnica do projeto MicroMouse (Lui) da UnB Gama.
repo_url: https://github.com/fcte-pi1/2026.1_PI1_Grupo2_Lui
repo_name: 2026.1_PI1_Grupo2_Lui
copyright: "Copyright &copy; 2026 UnB Gama - Projeto Integrador 1"

# Extensões Globais (CSS e JS)
extra_css:
  - assets/css/custom-general.css
  - assets/css/maze-bg.css

extra_javascript:
  - assets/js/maze-bg.js
  - assets/js/perfect_embed.js
  - assets/js/mathjax.js
  - assets/js/header-extras.js
  - assets/js/secondary-nav.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

  

# Plugins Ativos
plugins:
  - search

# Extensões Markdown
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

# Configuração de Tema (Material Design)
theme:
  name: material
  language: pt-BR
  logo: assets/images/ratinho.svg
  favicon: assets/images/ratinho.svg
  
  font:
    text: Roboto Mono
    code: Roboto Mono

  # Esquema de cores: Terminal/Dark (Slate)
  palette:
    - scheme: slate
      primary: deep purple
      accent: deep purple

  # Recursos de Interface e Navegação
  features:
    - navigation.instant        # Carregamento via AJAX acelerado
    - navigation.tracking       # Atualiza URL conforme scroll
    - navigation.tabs           # Menu superior em abas
    - navigation.tabs.sticky    # Abas fixas no topo
    - navigation.sections       # Agrupamento lógico de seções
    - navigation.footer         # Navegação no rodapé
    - navigation.indexes        # Link direto para índices de seção
    - navigation.top            # Botão de voltar ao topo
    
    - search.suggest            # Sugestão de pesquisa em tempo real
    - search.highlight          # Destaque de termos buscados
    - header.autohide           # Retração do header no scroll down
    
    - content.code.annotate     # Comentários interativos no código
    - content.code.copy         # Botão de copiar snippet
    - announce.dismiss          # Barra de anúncio dispensável

# Estrutura de Navegação (Menu)
nav:
  - Home: index.md
  - Energia: energia/energia.md
  - Hardware:
      - Visão Geral: hardware/hardware.md
      - EAP: hardware/hw_eap.md
  - Software:
      - Visão Geral: software/software.md
      - Requisitos e Backlog:
          - Histórias de Usuário: software/entrega_1/historias_usuario.md
          - Requisitos Não-Funcionais: software/entrega_1/requisitos_nao_funcionais.md
      - Modelagem e Fluxos:
          - BPMN (Processos): software/entrega_1/diagrama_bpmn.md
          - Casos de Uso: software/entrega_1/diagrama_casos_uso.md
          - Diagrama de Estados: software/entrega_1/diagrama_estados.md
      - Arquitetura:
          - Estrutura do Sistema: software/entrega_1/diagrama_arquitetura.md
          - DER (Banco de Dados): software/entrega_1/diagrama_der.md
      - Testes:
          - Matriz de Testes Funcionais: software/entrega_1/matriz_testes_funcionais.md
  - Estrutura: estrutura/estrutura.md
